### ISSUE TITLE
Drink List

### ISSUE THREAD

**Issue by JonLMyers** [KoalaTea/ChambordPi#10]
As a guest I want the ability to view a drink list with the ingredients for each drink.  Additionally I want to see the quantity of remaining ingredients and the number of credits for each drink.  Eventually we will add the stock exchange simulator to this page.

**Comment by KoalaTea** [comment]
There is  a menu, and a drink list. Menu is list of available drinks, drink list is all drinks. A Guest does not get to just see the available ingredients, will be available in custom drink though
