### ISSUE TITLE
Anti-Session Fixation

### ISSUE THREAD

**Issue by JonLMyers** [KoalaTea/ChambordPi#3]
As a web app I do not want to be vulnerable to session fixation attacks. This would make my guests and hosts very sad. Please make sure the session is changed to another random string following a successful login.

**Comment by JonLMyers** [comment]
As a web app I do not want to be vulnerable to session fixation attacks.  This would make my guests and hosts very sad.  Please make sure the session is changed to another random string following a successful login.

**Comment by KoalaTea** [comment]
There is no session tracking for an unauthenticated user. Upon login you will gain your session;
